Handling Missing Data

In [2]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

float_data.isna()

string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

string_data.isna()

data1 = pd.Series([1, np.nan, 3.5, np.nan, 7])
data1

data1.dropna()
data1[data1.notna()] #same as above

#CONTINUE FROM 224

data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

data.dropna()
data.dropna(how="all")

data[4] = np.nan #this will add a new COLUMN with NaN values
# data.loc[4] = np.nan #this will add a new ROW with NaN values
data

data = data.dropna(how="all",axis="columns")
print(data)

df = pd.DataFrame(np.random.randn(7,3))
print(df)

df.iloc[:4,1] = np.nan
df.iloc[:2,2] = np.nan
print(df)

df.dropna()

df.dropna(thresh=0) #The thresh parameter does not count how many NaN values to remove. Instead, it specifies the 
                    #minimum number of valid, non-missing values a row must have to be kept. if i set thresh = 1 then there must be atleast one non-NaN value row

df.fillna(0)
df.fillna({1: 0.5, 2: 0})
df.ffill()

data1 = pd.Series([1., np.nan, 3.5, np.nan, 7])
data1.fillna(data1.mean())
data[data.notna()]

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0
          0         1         2
0  0.482782 -0.078301 -1.145517
1  1.030474 -0.020844 -0.171517
2  2.332422 -1.937889 -0.670333
3  2.134483  0.389867 -1.253520
4 -0.305181 -1.133570  0.371456
5 -0.169024 -0.861494 -0.994999
6 -0.640461 -0.610091 -1.376704
          0         1         2
0  0.482782       NaN       NaN
1  1.030474       NaN       NaN
2  2.332422       NaN -0.670333
3  2.134483       NaN -1.253520
4 -0.305181 -1.133570  0.371456
5 -0.169024 -0.861494 -0.994999
6 -0.640461 -0.610091 -1.376704

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

Data Transformation

In [3]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
         "k2": [1, 1, 2, 3, 3, 4, 4]})
print(data)
data.duplicated()   
data.drop_duplicates() #last two rows were same so they are removed
data["v1"] = np.arange(7)
data
print(data.drop_duplicates(subset=["k2"]))
data.drop_duplicates(subset=["k2"],keep="last")

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4
    k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

    k1  k2  v1
1  two   1   1
2  one   2   2
4  one   3   4
6  two   4   6

Transforming Data Using a Function or Mapping

In [4]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
    "pastrami", "corned beef", "bacon",
    "pastrami", "honey ham", "nova lox"],
    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

meat_to_animal = {
 "bacon": "pig",
 "pulled pork": "pig",
 "pastrami": "cow",
 "corned beef": "cow",
 "honey ham": "pig",
 "nova lox": "salmon"
}

data["animal"] = data["food"].map(meat_to_animal)
data
#above method method 1(preffered)

# def get_animal(x):
#     return meat_to_animal[x]

# data["animal"] = data["food"].map(get_animal)
# data
# still method 1 preffered

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

Replacing Values

In [5]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

data.replace(-999,np.nan)
data.replace([-999,-1000],np.nan)
data.replace([-999,-1000],[np.nan,0])
data.replace({-999:np.nan,
              -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

Renaming Axis Indexes

In [6]:
data = pd.DataFrame(np.arange(12).reshape(3,4),
                    index = ["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])
data

#Now the real thing

def transform(x):
    return x[:4].upper()

data.index.map(transform)
data.index = data.index.map(transform)
data
data.rename(index=str.title,columns=str.upper)

data.rename(index={"OHIO": "INDIANA"},
        columns={"three": "peekaboo"})

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

Discretization and Binning

In [7]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

age_categories = pd.cut(ages, bins)
age_categories
age_categories.codes
age_categories.categories
age_categories.categories[0]
age_categories.value_counts()
pd.cut(ages,bins,right=False)

group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

age_categories = pd.cut(ages,bins,labels=group_names)
age_categories

data = np.random.uniform(size=20)
print(data)

d1 = pd.cut(data,4,precision=2)
print(d1.value_counts()) #difference in qcut and cut

data = np.random.standard_normal(100)
print(data)

quartiles = pd.qcut(data,4,precision=2)
quartiles
quartiles.value_counts() #difference in qcut and cut

print(pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts())
data.max()

age_categories

[0.44871725 0.5543202  0.44984904 0.47729228 0.70507503 0.77824952
 0.31953327 0.94700931 0.38058564 0.10319858 0.01611757 0.27327826
 0.6284888  0.26735788 0.65136649 0.75294446 0.17554884 0.49505389
 0.15338858 0.31020619]
(0.015, 0.25]    4
(0.25, 0.48]     8
(0.48, 0.71]     5
(0.71, 0.95]     3
Name: count, dtype: int64
[-7.14806495e-01  5.96220229e-01 -1.48792204e+00 -6.27447425e-01
 -8.13234764e-01  1.40213505e-01 -9.08519306e-01  4.04738827e-01
 -5.54418509e-01  1.26608209e+00  2.21095359e-01  3.80788864e-01
  1.33977453e+00  2.00763475e-01  4.69166398e-01  2.10511470e+00
 -9.70241878e-04  7.34146738e-01 -9.78741134e-01 -1.25674329e+00
  2.49600127e-01 -8.83097999e-01 -1.14567348e+00 -7.66802729e-01
 -2.31825695e+00  1.34490720e+00  1.08487741e-01  6.26707558e-01
  8.39629669e-01 -6.25228946e-01  1.89617498e+00  9.73038979e-02
  4.91119013e-02 -1.18943236e+00 -9.68133377e-01 -7.29813190e-01
 -1.20374530e-01  8.90500043e-01  6.14699380e-01 -8.09589758e-01
  1.33181151e+00  1.90897037e+00  2.56719248e-01  6.34337007e-01
  9.66482802e-02 -3.15716611e-01 -3.30872178e-01  2.89269164e-01
 -5.57818415e-01  1.19916979e+00  9.32794285e-01  2.42970693e-01
 -1.30316250e-01 -1.47599103e+00  1.45944523e+00 -1.52613426e+00
 -3.98079381e-01 -5.09807131e-01 -2.10493198e-01 -5.74914741e-01
 -6.44095451e-01 -1.80202519e-01  8.63323260e-01  5.27257641e-01
  6.30936172e-01 -9.96733191e-01 -1.01756208e+00 -1.59966409e-01
  2.24870567e+00 -3.92988121e-01  5.39062275e-01  1.33658839e+00
  2.33713576e+00 -8.72265387e-01  6.91142784e-01 -9.03291891e-01
 -2.41432228e+00 -1.02904291e-01  8.01436575e-01  5.14990945e-01
  8.16332980e-01  3.89291265e-01 -1.35010986e+00  1.15549357e-01
 -1.12893808e+00 -3.13344162e-01  3.09822402e-01 -2.27002241e+00
 -5.52176823e-01  2.38099150e+00 -1.00329748e-01  1.29285950e+00
  1.29933196e-01 -1.29651207e+00 -8.79905403e-01 -8.44117725e-01
 -4.30584092e-01 -1.44604356e-01  9.07918567e-01  4.38070402e-02]
(-2.415, -1.15]    10
(-1.15, 0.0214]    40
(0.0214, 1.332]    40
(1.332, 2.381]     10
Name: count, dtype: int64

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, str): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

Detecting and Filtering Outliers

In [8]:
data = pd.DataFrame(np.random.randn(1000, 4))
print(data)
data.describe()

col = data[1]
col[col.abs() > 3]

data[(data.abs() > 3).any(axis="columns")]
data[((data >= -3) & (data <= 3)).any(axis="columns")] #method 1

#method 2
data[data.abs() > 3] = np.sign(data) * 3
data
print(data.abs() < 1)
print(data[data.abs() < 1])
data.describe()

            0         1         2         3
0   -0.124173  1.410468 -0.688462 -0.767966
1    1.291010 -0.653554 -0.742077 -0.306612
2   -0.126850 -0.479277  1.317816  0.670219
3    1.310412 -1.060720  1.164277 -0.028501
4    1.678369  1.171482 -0.590582 -0.316983
..        ...       ...       ...       ...
995  2.795602  1.367834  1.143064 -0.595407
996  1.153913  1.751308 -0.073800  0.446108
997 -0.651761  1.039199 -1.048068  0.885471
998 -0.118205  0.942364  0.409610  0.239910
999 -0.635972  0.282424  0.518006 -0.294110

[1000 rows x 4 columns]
         0      1      2     3
0     True  False   True  True
1    False   True   True  True
2     True   True  False  True
3    False  False  False  True
4    False  False   True  True
..     ...    ...    ...   ...
995  False  False  False  True
996  False  False   True  True
997   True  False  False  True
998   True   True   True  True
999   True   True   True  True

[1000 rows x 4 columns]
            0         1         2         3
0   -0.124173       NaN -0.688462 -0.767966
1         NaN -0.653554 -0.742077 -0.306612
2   -0.126850 -0.479277       NaN  0.670219
3         NaN       NaN       NaN -0.028501
4         NaN       NaN -0.590582 -0.316983
..        ...       ...       ...       ...
995       NaN       NaN       NaN -0.595407
996       NaN       NaN -0.073800  0.446108
997 -0.651761       NaN       NaN  0.885471
998 -0.118205  0.942364  0.409610  0.239910
999 -0.635972  0.282424  0.518006 -0.294110

[1000 rows x 4 columns]

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.022360     0.031642    -0.007227     0.070022
std       1.031718     0.961162     1.031106     0.975270
min      -3.000000    -2.925612    -3.000000    -3.000000
25%      -0.683934    -0.628743    -0.701267    -0.537137
50%       0.004366     0.046551     0.025671     0.039238
75%       0.665145     0.665538     0.699148     0.690322
max       3.000000     3.000000     3.000000     3.000000

Permutation and Random Sampling

In [9]:
df = pd.DataFrame(np.arange(35).reshape((5, 7)))
df

sampler = np.random.permutation(5)
sampler

df.take(sampler)
df.iloc[sampler] #both this and above same

column_sampler = np.random.permutation(7)
column_sampler

df.take(column_sampler,axis="columns")
df.iloc[:,column_sampler] # both this and above is same

df.sample(3)

choices = pd.Series([5, 7, -1, 6, 4])
choices.sample(10,replace=True)

1    7
2   -1
0    5
3    6
4    4
1    7
3    6
0    5
1    7
3    6
dtype: int64

Computing Indicator/Dummy Variables

In [23]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})
df

pd.get_dummies(df["key"],dtype=int)

dummies = pd.get_dummies(df["key"], prefix="key")
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("datasets/movielens/movies.dat", sep="::",
                       header=None, names=mnames, engine="python")
movies

dummies = movies["genres"].str.get_dummies("|")
dummies
dummies.iloc[:10,:6]

movies_windic = movies.join(dummies.add_prefix("Genre"))
movies_windic.iloc[0]
movies.join(dummies).iloc[0]

np.random.seed(12345) # to make the example repeatable

values = np.random.uniform(size=6)
values

bin = [0, 0.2, 0.4, 0.6, 0.8, 1]
print(values)
pd.cut(values,bin)

pd.get_dummies(pd.cut(values,bin),dtype=int)

[0.92961609 0.31637555 0.18391881 0.20456028 0.56772503 0.5955447 ]

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0

Extension Data Types

In [11]:
s = pd.Series([1, 2, 3, None])
s

s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())
s
s.isna()
s = pd.Series([1, 2, 3, None], dtype="Int64") #also works

s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())
s

df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})

df

df["A"] = df["A"].astype("Int64")
df["B"] = df["B"].astype("string")
df

      A      B      C
0     1    one  False
1     2    two   None
2  <NA>  three  False
3     4   <NA>   True

String Manipulation

Python Built-In String Object Methods

In [12]:
val = "a,b, guido"
val.split(",")
pieces = [x.strip() for x in val.split(",")]
pieces

first, second, third = pieces
first + "::" + second + "::" + third

"::".join(pieces)

"guido" in val
val.index(",") #will give an error if not found
val.find(":") #string not found

val.count(",")
val.replace(",","::")
val.replace(",","")

'ab guido'

Regular Expressions

In [13]:
import re

text = "foo bar\t baz \tqux"
text

re.split(r"\s+",text)

regex = re.compile(r"\s+")
regex.split(text)
regex.findall(text)

text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

regex = re.compile(pattern,flags=re.IGNORECASE)
regex.findall(text)

m = regex.search(text)
m

text[m.start():m.end()] #note this will look at Dave dave@google.com and if you write m.start() which is at 5th position 
                        #and m.end() is where the index ends which is 20 (right after com) so writing [m.start():6] will give you letter 'd'

print(regex.match(text))
print(regex.sub("SAME", text))

pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})" #NOTE : THIS IS DIFFERENT FROM THE AABOE
regex = re.compile(pattern, flags=re.IGNORECASE)

m = regex.match("wesm@bright.net")
m
m.groups()

regex.findall(text)

print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text)) # HERE SPECIAL SYMBOLS \1 MATCH THE GROUPS FIRST PART AND SO ON

None
Dave SAME
Steve SAME
Rob SAME
Ryan SAME
Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com

String Functions in pandas

In [14]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}
data

data = pd.Series(data)
data
data.isna()

data.str.contains("gmail")

data_as_string_ext = data.astype('string')
data_as_string_ext

data_as_string_ext.str.contains("gmail")

pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern,flags=re.IGNORECASE)

matches = data.str.findall(pattern,flags=re.IGNORECASE).str[0]
matches

matches.str.get(1)
data.str[:5]

data.str.extract(pattern, flags=re.IGNORECASE)

           0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

Background and Motivation Behind Categories

In [15]:
values = pd.Series(['apple', 'orange', 'apple',
                    'apple'] * 2)
values

pd.unique(values)
values.value_counts()

values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(['apple', 'orange'])
values
dim
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: str

Categorical Extension Type in pandas

In [16]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)
rng

df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
  columns=['basket_id', 'fruit', 'count', 'weight'])
df

fruit_cat = df["fruit"].astype('category')
fruit_cat

#NOW
c = fruit_cat.array
type(c)
c.categories
c.codes

dict(enumerate(c.categories))

df['fruit'] = df['fruit'].astype('category')
df['fruit']

my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

categoriesss = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]

my_cats_2 = pd.Categorical.from_codes(codes,categoriesss)
my_cats_2

ordered_cat = pd.Categorical.from_codes(codes,categoriesss,ordered=True)
ordered_cat

my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, str): ['foo' < 'bar' < 'baz']

Computations with Categoricals

In [17]:
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)
draws[:5]

bins = pd.qcut(draws,4)
bins

bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins

bins.codes[:10]

bins = pd.Series(bins,name='quartile')

results = pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index()
results
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

Better performance with categoricals

In [18]:
N = 10_000_000
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

categories = labels.astype('category')

labels.memory_usage(deep=True)
categories.memory_usage(deep=True)

%time _  = labels.astype('category')
%time _

%timeit labels.value_counts()
%timeit categories.value_counts()

CPU times: total: 312 ms
Wall time: 310 ms
CPU times: total: 0 ns
Wall time: 1.67 μs
285 ms ± 2.16 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
40.1 ms ± 559 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

Categorical Methods

In [19]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

s = pd.Series(['a', 'b', 'c', 'd'] * 2)
cat_s = s.astype('category')
cat_s.cat.codes
cat_s.cat.categories

actual_categories = ['a', 'b', 'c', 'd', 'e']

cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

cat_s.value_counts()
cat_s2.value_counts()

cat_s3 = cat_s[cat_s.isin(['a','b'])]
cat_s3

cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, str): ['a', 'b']

Creating dummy variables for modeling

In [20]:
cat_s = pd.Series(['a','b','c','d'] * 2, dtype='category')
cat_s
pd.get_dummies(cat_s,dtype=int)

   a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1